### ISSUE TITLE
Ignores dir/file distinction from ZFVimIgnore

### ISSUE THREAD

**Issue by bartlibert** [ZSaberLv0/ZFVimDirDiff#28]
In ZFVimIgnore, you can specify dir and file matchers, but ZFVimDirDiff ignores this difference, leading to some wrong behaviour, for example:

- The default settings of ZFVimIgnore contain a file matcher `*.d` (I suppose to ignore dependency files generated by compilers)
- ZFVimDirDiff uses this `*.d` too match directories as well, so directories ending with .d are ignored as well, which is a pity, as on linux those are used quite a bit (e.g. `/etc/conf.d`).

I don't know if you want to make this distinction in this plugin, if not, you can close this and I'll use ZFIgnoreOff as a workaround in these cases.

**Comment by ZSaberLv0** [comment]
`diff -X excludefile` does not support to specify exclude `file or dir`, so there's no simple way to solve this issue for now (I have removed the default `*.d` for ZFVimIgnore)

---

PS: for a long time, I was thinking of rebuild this plugin by using `glob()` to list and diff dirs/files instead of plain `diff`, which should solve this issue
but that would bring much more performance issue, thus async mode and cache logic is necessary, I have no enough time recently, so maybe later

**Comment by ZSaberLv0** [comment]
https://github.com/ZSaberLv0/ZFVimDirDiff/commit/7610fc4a42f3dbc012c772e633b80eecd48a805f
@bartlibert here comes the fully async version, and the `file` and `dir` ignore settings would take proper effect
also remember to install `ZSaberLv0/ZFVimJob` as it becomes a required dependency of new version
